{% set name = "spherical" %}
{% set version = "1.0.14" %}
{% set sha256 = "a9de448a02c84734cd8829ebeca5fe0ade1f6bd249fb081e2cfc1f528499ff2f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip >=20.0.2
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - numba
    - quaternionic >=1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - spherical

about:
  home: https://github.com/moble/spherical
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Evaluate and transform D matrices, 3-j symbols, and (scalar or spin-weighted) spherical harmonics
  description: |
    This package provides efficient, accurate, and numerically stable code to compute various
    spherical functions and related quantities.  The code is written in pure python, but is
    automatically compiled with numba for greater efficiency.
  dev_url: https://github.com/moble/spherical
  doc_url: https://spherical.readthedocs.io/

extra:
  recipe-maintainers:
    - moble
